<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>View URL</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</head>
<body class="min-vh-100 d-flex flex-column">
    <header>
        <nav class="navbar navbar-expand-md navbar-dark bg-dark" data-bs-theme="dark">
            <div class="container-fluid">
                <a class="navbar-brand" href="/">Анализатор страниц</a>
                <button 
                    class="navbar-toggler" 
                    type="button" 
                    data-bs-toggle="collapse" 
                    data-bs-target="#navbarNavDropdown" 
                    aria-controls="navbarNavDropdown" 
                    aria-expanded="false" 
                    aria-label="Toggle navigation"
                >
                <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="/">Главная</a>
                        </li>
                        <li class="nav-item">
                        <a class="nav-link" href="/urls">Сайты</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <main class="flex-grow-1">
    <?php if (!$flash == null) : ?>
        <?php foreach ($flash as $status => $messages) : ?>
            <?php foreach ($messages as $message) : ?>
                <div class="alert alert-<?=htmlspecialchars($status)?>" role="alert">
                    <?= htmlspecialchars($message)?>
                </div>
            <?php endforeach ?>
        <?php endforeach?>
    <?php endif ?>
        <div class="container-lg">
            <h1 class="mt-3">Сайт: <?= htmlspecialchars($url->name)?></h1>
            <div class="row">
                <div class="col">
                    <table class="table table-bordered table-responsive text-nowrap table-hover" data-test="url">
                        <tbody class="fw-normal">
                                <tr>
                                    <td>ID</td>
                                    <td><?= htmlspecialchars($url->id)?></td>
                                <tr>
                                    <td>Имя</td>
                                    <td><?= htmlspecialchars($url->name)?></td>
                                </tr>
                                <tr>
                                    <td>Дата создания</td>
                                    <td><?= htmlspecialchars($url->created_at)?></td>
                                </tr>
                        </tbody>
                    </table>
                </div>
            </div>
            <h2 class="mt-5">Проверки</h2>
            <form action="/urls/<?= htmlspecialchars($url->id)?>/checks" class="my-3" method="post">
                <input type="submit" class="btn btn-primary" value="Запустить проверку">
            </form>
            <table class="table table-bordered table-responsive" data-test="checks">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Код ответа</th>
                        <th>h1</th>
                        <th>title</th>
                        <th>description</th>
                        <th>Дата создания</th>
                    </tr>
                </thead>
                <tbody>
                    <?php if (isset($checks)) : ?>
                        <?php foreach ($checks as $check) : ?>
                            <tr>
                                <td>
                                    <?= htmlspecialchars($check->id) ?>
                                </td>
                                <td>
                                    <?= htmlspecialchars($check->status_code ?? '') ?>
                                </td>
                                <td>
                                    <?= htmlspecialchars($check->h1 ?? '') ?>
                                </td>
                                <td>
                                    <?= htmlspecialchars($check->title ?? '') ?>
                                </td>
                                <td>
                                    <?= htmlspecialchars($check->description ?? '') ?>
                                </td>
                                <td>
                                    <?= htmlspecialchars($check->created_at) ?>
                                </td>
                            </tr>
                        <?php endforeach ?>
                    <?php endif ?>
                </tbody>
            </table>
        </div>
    </main>
    <footer class="border-top py-3">
        <div class="container-lg">
            <div class="text-center">
                <a href="#">Hexlet</a>
            </div>
        </div>
    </footer>
</body>
</html>
